
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: projectrr-api_development


test:
  <<: *default
  database: projectrr-api_test


production:
  <<: *default
  database: projectrr-api_production
  username: projectrr-api
  password: <%= ENV['PROJECTRR-API_DATABASE_PASSWORD'] %>
